"""Role Coloumn added

Revision ID: 3f5c92072938
Revises: 567fd800713a
Create Date: 2025-06-11 20:26:45.844700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f5c92072938'
down_revision: Union[str, None] = '567fd800713a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    userrole_enum = sa.Enum('admin', 'user', name='userrole')
    userrole_enum.create(op.get_bind())
    op.add_column('users', sa.Column('role', sa.Enum('admin', 'user', name='userrole'), server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    sa.Enum(name='userrole').drop(op.get_bind())
    # ### end Alembic commands ###
